// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRkhlbj_PqiOzLnNUK43eTA9B29vBCATA',
    appId: '1:1019230094129:web:8e28da4615a0c086b7a610',
    messagingSenderId: '1019230094129',
    projectId: 'alphadatabase-6609c',
    authDomain: 'alphadatabase-6609c.firebaseapp.com',
    databaseURL: 'https://alphadatabase-6609c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphadatabase-6609c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBxe-hTMVAf5hvgvoBYeMCRSyzElN1ZU',
    appId: '1:1019230094129:android:b442f2e2bfa05307b7a610',
    messagingSenderId: '1019230094129',
    projectId: 'alphadatabase-6609c',
    databaseURL: 'https://alphadatabase-6609c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphadatabase-6609c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzoEUALTvWRVSnBTuUblUOK2CHbv0jnZI',
    appId: '1:1019230094129:ios:49fdf6218bc02654b7a610',
    messagingSenderId: '1019230094129',
    projectId: 'alphadatabase-6609c',
    databaseURL: 'https://alphadatabase-6609c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphadatabase-6609c.appspot.com',
    iosClientId: '1019230094129-ndq9i3ilop51p5s0nmiagi1o2k2vg5kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chandanFlutterCodes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzoEUALTvWRVSnBTuUblUOK2CHbv0jnZI',
    appId: '1:1019230094129:ios:a93289144055806ab7a610',
    messagingSenderId: '1019230094129',
    projectId: 'alphadatabase-6609c',
    databaseURL: 'https://alphadatabase-6609c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphadatabase-6609c.appspot.com',
    iosClientId: '1019230094129-lg1gme3kvitavmd52hmo4g368vjq3b2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphaApp',
  );
}
